var reportData = {
    "codeInfo": "操作成功！",
    "code": 0,
    "objects": {
        "enable": true,
        "gearboxtype": "22",
        "handstrapdrivertype": "30",
        "handstraptype": "50",
        "height": "50",
        "id": 1,
        "inclination": "60",
        "isdelete": false,
        "liftno": "12",
        "motorpower": "50",
        "motortype": "1",
        "name": "11",
        "performanceid": 2,
        "performanceset": {
            "alarmdelay": "50",
            "createtime": "2017-02-06 17:54:14",
            "electricity": "10.22",
            "enable": true,
            "energy2a": "40",
            "energy3a": "50",
            "energy4a": "60",
            "energya": "30",
            "energyalarm": "12",
            "energyalarmtype": "1",
            "energyb": "20",
            "energyc": "10",
            "energyd": "5",
            "energyoffset": "1",
            "id": 2,
            "isdelete": true,
            "name": "测试性能",
            "noise": "50",
            "operator": "lvbm",
            "signaldelay": "40",
            "speed": "100.2",
            "vibration": "20.03",
            "voltage": "50"
        },
        "productline": "L211",
        "report": {
            "createtime": "2016-01-01 12:00:00",
            "downfloorvmax": "2",
            "downnoise": "2",
            "downpoweravg": "2",
            "downvmax": "2",
            "id": 1,
            "lefthandrialup": "2",
            "recordid": 1,
            "righthandrialdown": "2",
            "speed": "20",
            "upfloorvmax": "2",
            "upnoise": "2",
            "uppoweravg": "2",
            "upvmax": "2"
        },
        "retestrecords": [{
            "date": "2016-01-01 12:00:00",
            "enable": false,
            "id": 1,
            "isdelete": false,
            "name": "12",
            "operator": "ly",
            "testrecordid": 1
        }],
        "runmode": "3",
        "speed": "40",
        "testdate": "2016-01-01 12:00:00",
        "testjobid": 30,
        "testoperator": "ly",
        "teststeps": [{
            "controltype": 1,
            "id": 30,
            "isdelete": false,
            "jobid": 30,
            "steporder": 1,
            "testtime": "60",
            "unitids": "3",
            "unitnames": "a21322"
        }],
        "width": "20"
    }
}
